---
- name: Deploy app
  hosts: all
  vars_files:
    - vars/app.yml
    - vars/deploy.yml
  roles:
    - role: carlosbuenosvinos.ansistrano-rollback
      become: true
      become_user: "{{ app_user }}"
